package com.example.stramitapp.repositories//package com.example.stramitapp.repositories

//
//class AppRepository {
//
//    val applicationDataStore = ApplicationDataStore()
//    val assetDataStore = AssetDataStore()
//    val assetConditionDataStore = AssetConditionDataStore()
//    val assetMovementInfoDataStore = AssetMovementInfoDataStore()
//    val assetStatusDataStore = AssetStatusDataStore()
//    val attributeDataStore = AttributeDataStore()
//    val attributePreferenceDataStore = AttributePreferenceDataStore()
//    val attributeTableDataStore = AttributeTableDataStore()
//    val companyDataStore = CompanyDataStore()
//    val companyAssetCategoryDataStore = CompanyAssetCategoryDataStore()
//    val companyAssetPartsDataStore = CompanyAssetPartsDataStore()
//    val companyAssetSubPartsDataStore = CompanyAssetSubPartsDataStore()
//    val companyAssetTypeDataStore = CompanyAssetTypeDataStore()
//    val companyLocationDataStore = CompanyLocationDataStore()
//    val deviceTypeDataStore = DeviceTypeDataStore()
//    val jobDescriptionDataStore = JobDescriptionDataStore()
//    val jobAssetTrackInfoDataStore = JobAssetTrackInfoDataStore()
//    val jobTypeDataStore = JobTypeDataStore()
//    val licenseeDataStore = LicenseeDataStore()
//    val licenseeConfigDataStore = LicenseeConfigDataStore()
//    val licenseePeerDataStore = LicenseePeerDataStore()
//    val mobileJobDataStore = MobileJobDataStore()
//    val rightsDataStore = RightsDataStore()
//    val roleDataStore = RoleDataStore()
//    val roleToRightsMappingDataStore = RoleToRightsMappingDataStore()
//    val settingsDataStore = SettingsDataStore()
//    val userDataStore = UserDataStore()
//    val userRoleDataStore = UserRoleDataStore()
//    val wpCompanyDataStore = WpCompanyDataStore()
//
//    val assetFinancialInfoDataStore = AssetFinancialInfoDataStore()
//    val assetInspectionInfoDataStore = AssetInspectionInfoDataStore()
//    val assetInsuranceInfoDataStore = AssetInsuranceInfoDataStore()
//    val assetIssueImagesDataStore = AssetIssueImagesDataStore()
//    val assetIssueInfoDataStore = AssetIssueInfoDataStore()
//    val assetLeaseInfoDataStore = AssetLeaseInfoDataStore()
//    val assetMaintenanceInfoDataStore = AssetMaintenanceInfoDataStore()
//    val assetMemoInfoDataStore = AssetMemoInfoDataStore()
//    val billOfMaterialDataStore = BillOfMaterialDataStore()
//    val jobAssignmentDataStore = JobAssignmentDataStore()
//    val jobDefinitionDataStore = JobDefinitionDataStore()
//}