package com.example.stramitapp.Repositories//package com.example.stramitapp.Repositories

//import com.example.stramitapp.Repositories.DataStore.*
//import com.example.stramitapp.services.localDataStore.*
//
//class AppRepository {
//    val applicationDataStore: ApplicationDataStore = ApplicationDataStore()
//    val assetDataStore: AssetDataStore = AssetDataStore()
//    val assetConditionDataStore: AssetConditionDataStore = AssetConditionDataStore()
//    val assetMovementInfoDataStore: AssetMovementInfoDataStore = AssetMovementInfoDataStore()
//    val assetStatusDataStore: AssetStatusDataStore = AssetStatusDataStore()
//    val attributeDataStore: AttributeDataStore = AttributeDataStore()
//    val attributePreferenceDataStore: AttributePreferenceDataStore = AttributePreferenceDataStore()
//    val attributeTableDataStore: AttributeTableDataStore = AttributeTableDataStore()
//    val companyDataStore: CompanyDataStore = CompanyDataStore()
//    val companyAssetCategoryDataStore: CompanyAssetCategoryDataStore = CompanyAssetCategoryDataStore()
//    val companyAssetPartsDataStore: CompanyAssetPartsDataStore = CompanyAssetPartsDataStore()
//    val companyAssetSubPartsDataStore: CompanyAssetSubPartsDataStore = CompanyAssetSubPartsDataStore()
//    val companyAssetTypeDataStore: CompanyAssetTypeDataStore = CompanyAssetTypeDataStore()
//    val companyLocationDataStore: CompanyLocationDataStore = CompanyLocationDataStore()
//    val deviceTypeDataStore: DeviceTypeDataStore = DeviceTypeDataStore()
//    val jobDescriptionDataStore: JobDescriptionDataStore = JobDescriptionDataStore()
//    val jobTypeDataStore: JobTypeDataStore = JobTypeDataStore()
//    val licenseeDataStore: LicenseeDataStore = LicenseeDataStore()
//    val licenseeConfigDataStore: LicenseeConfigDataStore = LicenseeConfigDataStore()
//    val licenseePeerDataStore: LicenseePeerDataStore = LicenseePeerDataStore()
//    val mobileJobDataStore: MobileJobDataStore = MobileJobDataStore()
//    val rightsDataStore: RightsDataStore = RightsDataStore()
//    val roleDataStore: RoleDataStore = RoleDataStore()
//    val roleToRightsMappingDataStore: RoleToRightsMappingDataStore = RoleToRightsMappingDataStore()
//    val settingsDataStore: SettingsDataStore = SettingsDataStore()
//    val userDataStore: UserDataStore = UserDataStore()
//    val userRoleDataStore: UserRoleDataStore = UserRoleDataStore()
//    val wpCompanyDataStore: WpCompanyDataStore = WpCompanyDataStore()
//
//    val assetFinancialInfoDataStore: AssetFinancialInfoDataStore = AssetFinancialInfoDataStore()
//    val assetInspectionInfoDataStore: AssetInspectionInfoDataStore = AssetInspectionInfoDataStore()
//    val assetInsuranceInfoDataStore: AssetInsuranceInfoDataStore = AssetInsuranceInfoDataStore()
//    val assetIssueImagesDataStore: AssetIssueImagesDataStore = AssetIssueImagesDataStore()
//    val assetIssueInfoDataStore: AssetIssueInfoDataStore = AssetIssueInfoDataStore()
//    val assetLeaseInfoDataStore: AssetLeaseInfoDataStore = AssetLeaseInfoDataStore()
//    val assetMaintenanceInfoDataStore: AssetMaintenanceInfoDataStore = AssetMaintenanceInfoDataStore()
//    val assetMemoInfoDataStore: AssetMemoInfoDataStore = AssetMemoInfoDataStore()
//    // val assetMemoTypeDataStore: AssetMemoTypeDataStore = AssetMemoTypeDataStore()
//    val billOfMaterialDataStore: BillOfMaterialDataStore = BillOfMaterialDataStore()
//    val jobAssetTrackInfoDataStore: JobAssetTrackInfoDataStore = JobAssetTrackInfoDataStore()
//    val jobAssignmentDataStore: JobAssignmentDataStore = JobAssignmentDataStore()
//    val jobDefinitionDataStore: JobDefinitionDataStore = JobDefinitionDataStore()
//    // val readerDataStore: ReaderDataStore = ReaderDataStore()
//    // val readerModel1DataStore: ReaderModel1DataStore = ReaderModel1DataStore()
//    // val readerModelDataStore: ReaderModelDataStore = ReaderModelDataStore()
//}