package com.example.stramitapp.ui.search_shipment
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

@Parcelize
data class ShipmentSearchResultItem(
    val assetId: Int?,
    val locationName: String = "",
    val custom13: String = "",
    val custom22: String = "",
    val companyAssetId: String = "",
    val custom17: String = "",
    val barcode: String = "",
    val title: String = "",
    val custom1: String = "",
    val custom2: String = "",
    val custom3: String = "",
    val custom4: String = "",
    val custom5: String = "",
    val custom6: String = "",
    val custom7: String = "",
    val custom8: String = "",
    val custom9: String = "",
    val custom10: String = "",
    val custom11: String = "",
    val custom12: String = "",
    val custom14: String = "",
    val custom15: String = "",
    val custom16: String = "",
    val custom18: String = "",
    val custom19: String = "",
    val custom20: String = "",
    val custom21: String = "",
    val custom23: String = "",
    val custom24: String = "",
    val custom25: String = "",
    val custom26: String = "",
    val custom27: String = "",
    val custom28: String = "",
    val custom29: String = "",
    val custom30: String = "",
    val custom31: String = "",
    val custom32: String = "",
    val custom33: String = "",
    val custom34: String = "",
    val custom35: String = "",
    val custom36: String = "",
    val weight: String = "",
    val weightUom: String = "",
    val assetValue: String = "",
    val purchaseDate: String = "",
    val createDate: String = ""
) : Parcelable
fun ShipmentSearchResultItem.toSearchResultItem(): com.example.stramitapp.ui.search_asset.SearchResultItem {
    return com.example.stramitapp.ui.search_asset.SearchResultItem(
        assetId = this.assetId,
        locationName = this.locationName,
        barcode = this.barcode,
        companyAssetId = this.companyAssetId,
        title = this.title,
        custom1 = this.custom1,
        custom2 = this.custom2,
        custom3 = this.custom3,
        custom4 = this.custom4,
        custom5 = this.custom5,
        custom6 = this.custom6,
        custom7 = this.custom7,
        custom8 = this.custom8,
        custom9 = this.custom9,
        custom10 = this.custom10,
        custom11 = this.custom11,
        custom12 = this.custom12,
        custom13 = this.custom13,
        custom14 = this.custom14,
        custom15 = this.custom15,
        custom16 = this.custom16,
        custom17 = this.custom17,
        custom18 = this.custom18,
        custom19 = this.custom19,
        custom20 = this.custom20,
        custom21 = this.custom21,
        custom22 = this.custom22,
        custom23 = this.custom23,
        custom24 = this.custom24,
        custom25 = this.custom25,
        custom26 = this.custom26,
        custom27 = this.custom27,
        custom28 = this.custom28,
        custom29 = this.custom29,
        custom30 = this.custom30,
        custom31 = this.custom31,
        custom32 = this.custom32,
        custom33 = this.custom33,
        custom34 = this.custom34,
        custom35 = this.custom35,
        custom36 = this.custom36,
        weight = this.weight,
        weightUom = this.weightUom,
        assetValue = this.assetValue,
        purchaseDate = this.purchaseDate,
        createDate = this.createDate,
        tag = "",
        serialNumber = "",
        longDesc = ""
    )
}